// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package com.bitsevn.projects.chat.core;

public interface ChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   * @return The greeting.
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
